import SwiftUI

// MARK: - Language

enum AppLanguage: String, CaseIterable {
    case german = "de"
    // english = "en"  — wird später wieder aktiviert

    var label: String {
        switch self {
        case .german: return "Deutsch"
        }
    }
    var flag: String {
        switch self {
        case .german: return "🇩🇪"
        }
    }
}

// MARK: - Translations

/// Alle UI-Strings, die in der App sichtbar sind.
/// Aufruf: tr("key") gibt den String der aktuellen Sprache zurück.
private let strings: [String: [String: String]] = [

    // ── Tab Bar ──────────────────────────────────────────────────
    "tab.map":          ["de": "Karte",        "en": "Map"],
    "tab.nearby":       ["de": "Umgebung",     "en": "Nearby"],
    "tab.active":       ["de": "Aktiv",        "en": "Active"],
    "tab.friends":      ["de": "Profil",       "en": "Profile"],
    "tab.settings":     ["de": "Einstellungen","en": "Settings"],

    // ── Feed ─────────────────────────────────────────────────────
    "feed.title":           ["de": "Umgebung",              "en": "Nearby"],
    "feed.friends_nearby":  ["de": "Freunde in der Nähe",   "en": "Friends Nearby"],
    "feed.public_drops":    ["de": "Öffentliche Drops",     "en": "Public Drops"],
    "feed.unavailable":     ["de": "Nicht verfügbar",       "en": "Unavailable"],
    "feed.popular_nearby":  ["de": "Beliebt in deiner Nähe","en": "Popular nearby"],
    "feed.open_for_all":    ["de": "Offen für alle",        "en": "Open for all"],
    "feed.join_now":        ["de": "Jetzt dazukommen",      "en": "Join Now"],
    "feed.im_in":           ["de": "Bin dabei!",            "en": "I'm in!"],
    "feed.im_coming":       ["de": "Ich komme vorbei",      "en": "I'm coming"],
    "feed.request_sent":    ["de": "Anfrage gesendet",      "en": "Request sent"],
    "feed.unlock":          ["de": "Freischalten",          "en": "Unlock"],
    "feed.close":           ["de": "Schließen",             "en": "Close"],
    "feed.leave":           ["de": "Verlassen",             "en": "Leave"],
    "feed.leave_drop":      ["de": "Drop verlassen?",       "en": "Leave Drop?"],
    "feed.leave_warning":   ["de": "Wenn du zwischen 5 und 30 Minuten nach dem Beitreten verlässt, zählt das als No-Show — die andere Person wartet vielleicht schon.",
                             "en": "Leaving between 5–30 minutes after joining counts as a no-show — the other person may already be waiting."],
    "feed.add_message":     ["de": "Kurze Nachricht hinzufügen", "en": "Add a quick message"],

    // ── Map ──────────────────────────────────────────────────────
    "map.recenter":         ["de": "Standort",              "en": "Location"],
    "map.sos":              ["de": "SOS",                   "en": "SOS"],
    "map.safety_info":      ["de": "Sicherheitsinfos",      "en": "Safety Info"],

    // ── Map Style ────────────────────────────────────────────────
    "map.style.auto":       ["de": "Auto (Tag/Nacht)",      "en": "Auto (Day/Night)"],
    "map.style.light":      ["de": "Immer hell",            "en": "Always Light"],
    "map.style.dark":       ["de": "Immer dunkel",          "en": "Always Dark"],

    // ── Create Drop ──────────────────────────────────────────────
    "create.title":         ["de": "Drop erstellen",        "en": "Create Drop"],
    "create.activity":      ["de": "Was machst du?",        "en": "What are you doing?"],
    "create.location":      ["de": "Wo?",                   "en": "Where?"],
    "create.description":   ["de": "Beschreibung",          "en": "Description"],
    "create.start":         ["de": "Wann startet es?",      "en": "When does it start?"],
    "create.drop":          ["de": "Drop erstellen",        "en": "Create Drop"],
    "create.now":           ["de": "Jetzt",                 "en": "Now"],
    "create.in_30":         ["de": "In 30 Min",             "en": "In 30 min"],
    "create.in_1h":         ["de": "In 1 Std",              "en": "In 1 hour"],
    "create.tonight":       ["de": "Heute Abend",           "en": "Tonight"],

    // ── Profile & Friends ────────────────────────────────────────
    "profile.title":        ["de": "Profil",                "en": "Profile"],
    "profile.friends":      ["de": "Freunde",               "en": "Friends"],
    "profile.reliability":  ["de": "Zuverlässigkeit",       "en": "Reliability"],
    "profile.drops":        ["de": "Drops",                 "en": "Drops"],
    "profile.history":      ["de": "Verlauf",               "en": "History"],
    "profile.edit":         ["de": "Bearbeiten",            "en": "Edit"],
    "profile.add_friend":   ["de": "Freund hinzufügen",     "en": "Add Friend"],
    "profile.block":        ["de": "Blockieren",            "en": "Block"],
    "profile.verified":     ["de": "Verifiziert",           "en": "Verified"],
    "profile.verify_now":   ["de": "Jetzt verifizieren",    "en": "Verify Now"],

    // ── Settings ─────────────────────────────────────────────────
    "settings.title":               ["de": "Einstellungen",             "en": "Settings"],
    "settings.visibility":          ["de": "Sichtbarkeit",              "en": "Visibility"],
    "settings.appearance":          ["de": "Darstellung",               "en": "Appearance"],
    "settings.language":            ["de": "Sprache",                   "en": "Language"],
    "settings.map_style":           ["de": "Kartenstil",                "en": "Map Style"],
    "settings.notifications":       ["de": "Push-Mitteilungen",         "en": "Push Notifications"],
    "settings.notifications_sub":   ["de": "Drops & Einladungen in der Nähe", "en": "Drops & invitations nearby"],
    "settings.safety":              ["de": "Sicherheit",                "en": "Safety"],
    "settings.radius":              ["de": "Drops Radius",              "en": "Drop Radius"],
    "settings.age_groups":          ["de": "Altersgruppen",             "en": "Age Groups"],
    "settings.legal":               ["de": "Rechtliches",               "en": "Legal"],
    "settings.privacy":             ["de": "Datenschutz",               "en": "Privacy Policy"],
    "settings.terms":               ["de": "Nutzungsbedingungen",       "en": "Terms of Service"],
    "settings.delete_account":      ["de": "Konto löschen",            "en": "Delete Account"],
    "settings.delete_confirm":      ["de": "Konto wirklich löschen?",   "en": "Delete Account?"],
    "settings.delete_warning":      ["de": "Alle deine Daten werden unwiderruflich gelöscht.", "en": "All your data will be permanently deleted."],
    "settings.logout":              ["de": "Abmelden",                  "en": "Sign Out"],
    "settings.location_sharing":    ["de": "Standort teilen",           "en": "Share Location"],
    "settings.location_sub":        ["de": "Freunde sehen deinen Pin", "en": "Friends can see your pin"],

    // ── Safety ───────────────────────────────────────────────────
    "safety.sos_activate":          ["de": "SOS aktivieren",            "en": "Activate SOS"],
    "safety.sos_active":            ["de": "SOS aktiv",                 "en": "SOS Active"],
    "safety.sos_deactivate":        ["de": "SOS beenden",               "en": "End SOS"],
    "safety.emergency_contact":     ["de": "Notfallkontakt",            "en": "Emergency Contact"],
    "safety.emergency_sub":         ["de": "Wird bei SOS benachrichtigt","en": "Notified during SOS"],
    "safety.not_set":               ["de": "Nicht eingestellt",         "en": "Not set"],
    "safety.id_verified":           ["de": "Alle per Ausweis-Scan verifiziert", "en": "All ID-verified users"],
    "safety.public_only":           ["de": "Öffentliche Orte",          "en": "Public Places"],

    // ── Onboarding ───────────────────────────────────────────────
    "onboarding.interests_title":   ["de": "Was magst du?",             "en": "What do you like?"],
    "onboarding.interests_sub":     ["de": "Wir zeigen dir passende Drops — deine Auswahl bleibt für andere unsichtbar.",
                                     "en": "We'll show you relevant Drops — your choices stay private."],
    "onboarding.max_select":        ["de": "Bis zu 5 auswählbar",       "en": "Pick up to 5"],
    "onboarding.skip":              ["de": "Überspringen",              "en": "Skip"],
    "onboarding.continue":          ["de": "Weiter",                    "en": "Continue"],

    // ── Welcome Sheet ────────────────────────────────────────────
    "welcome.title":                ["de": "Willkommen bei Drops",      "en": "Welcome to Drops"],
    "welcome.subtitle":             ["de": "Triff echte Leute in Echtzeit.", "en": "Meet real people in real time."],
    "welcome.cta":                  ["de": "Los geht's",                "en": "Let's go"],
    "welcome.feature1_title":       ["de": "Drop in deiner Nähe",       "en": "Drops Near You"],
    "welcome.feature1_sub":         ["de": "Sieh in Echtzeit, was in deiner Nähe passiert.", "en": "See what's happening around you in real time."],
    "welcome.feature2_title":       ["de": "Auf der Karte",             "en": "On the Map"],
    "welcome.feature2_sub":         ["de": "Finde Drops und Freunde direkt auf der Karte.", "en": "Find Drops and friends directly on the map."],
    "welcome.feature3_title":       ["de": "Freunde & neue Leute",      "en": "Friends & New People"],
    "welcome.feature3_sub":         ["de": "Alle sehen deinen Namen, dein Alter und dein Bild — triff Freunde oder lerne neue Leute kennen.", "en": "Everyone sees your name, age, and photo — meet friends or get to know new people."],
    "welcome.feature4_title":       ["de": "Sicher unterwegs",         "en": "Stay Safe"],
    "welcome.feature4_sub":         ["de": "SOS, Notfallkontakt und Ausweis-Verifizierung.", "en": "SOS, emergency contact, and ID verification."],

    // ── Common ───────────────────────────────────────────────────
    "common.cancel":    ["de": "Abbrechen",  "en": "Cancel"],
    "common.save":      ["de": "Speichern",  "en": "Save"],
    "common.done":      ["de": "Fertig",     "en": "Done"],
    "common.back":      ["de": "Zurück",     "en": "Back"],
    "common.close":     ["de": "Schließen",  "en": "Close"],
    "common.continue":  ["de": "Weiter",     "en": "Continue"],
    "common.skip":      ["de": "Überspringen","en": "Skip"],
    "common.confirm":   ["de": "Bestätigen", "en": "Confirm"],
    "common.delete":    ["de": "Löschen",    "en": "Delete"],
    "common.ok":        ["de": "OK",         "en": "OK"],
    "common.yes":       ["de": "Ja",         "en": "Yes"],
    "common.no":        ["de": "Nein",       "en": "No"],
    "common.error":     ["de": "Fehler",     "en": "Error"],
    "common.loading":   ["de": "Lädt...",    "en": "Loading..."],
    "common.verified":  ["de": "Verifiziert","en": "Verified"],
    "common.optional":  ["de": "Optional",   "en": "Optional"],

    // ── Interests ────────────────────────────────────────────────
    "interest.coffee":   ["de": "Kaffee",    "en": "Coffee"],
    "interest.drink":    ["de": "Drink",     "en": "Drinks"],
    "interest.sport":    ["de": "Sport",     "en": "Sport"],
    "interest.food":     ["de": "Essen",     "en": "Food"],
    "interest.gaming":   ["de": "Zocken",    "en": "Gaming"],
    "interest.music":    ["de": "Musik",     "en": "Music"],
    "interest.creative": ["de": "Kreatives", "en": "Creative"],
    "interest.cinema":   ["de": "Kino",      "en": "Cinema"],
    "interest.wellness": ["de": "Wellness",  "en": "Wellness"],
    "interest.outdoor":  ["de": "Draußen",   "en": "Outdoor"],
    "interest.shopping": ["de": "Shopping",  "en": "Shopping"],
    "interest.travel":   ["de": "Reisen",    "en": "Travel"],
    "interest.party":    ["de": "Ausgehen",  "en": "Going Out"],
    "interest.photo":    ["de": "Fotos",     "en": "Photos"],
    "interest.cooking":  ["de": "Kochen",    "en": "Cooking"],

    // ── Profile – Extended ───────────────────────────────────────
    "profile.online_nearby":              ["de": "Jetzt in der Nähe",                "en": "Online Nearby"],
    "profile.unavailable":                ["de": "Nicht verfügbar",                  "en": "Unavailable"],
    "profile.maybe_know":                 ["de": "Vielleicht kennst du",             "en": "Maybe You Know"],
    "profile.add":                        ["de": "Hinzufügen",                       "en": "Add"],
    "profile.coming_to_drop":             ["de": "Kommt vorbei",                     "en": "Coming to Drop"],
    "profile.recent_encounters":          ["de": "Letzte Begegnungen",               "en": "Recent Encounters"],
    "profile.recent_drops":               ["de": "Letzte Drops",                     "en": "Recent Drops"],
    "profile.host":                       ["de": "Host",                             "en": "Host"],
    "profile.add_from_contacts":          ["de": "Aus Kontakten hinzufügen",         "en": "Add From Contacts"],
    "profile.find_friends_using":         ["de": "Finde Freunde die Drops schon nutzen", "en": "Find Friends Already Using Drops"],
    "profile.share_invite_link":          ["de": "Einladungslink teilen",            "en": "Share Invite Link"],
    "profile.link_via_messaging":         ["de": "Link via WhatsApp, iMessage, etc.","en": "Link via WhatsApp, iMessage, etc."],
    "profile.was_host":                   ["de": "Du warst Host",                    "en": "You Were Host"],
    "profile.participants":               ["de": "Teilnehmer",                       "en": "Participants"],
    "profile.not_shown":                  ["de": "Nicht erschienen",                 "en": "No Show"],
    "profile.confirmed":                  ["de": "Getroffen",                        "en": "Confirmed"],
    "profile.detecting":                  ["de": "Wird erkannt…",                    "en": "Detecting..."],
    "profile.coming":                     ["de": "kommt vorbei",                     "en": "coming"],
    "profile.no_suggestions":             ["de": "Keine neuen Vorschläge",           "en": "No New Suggestions"],
    "profile.already_on_drops":           ["de": "Bereits auf Drops",               "en": "Already On Drops"],
    "profile.invite_all_via_link":        ["de": "Alle einladen via Link",           "en": "Invite All Via Link"],
    "profile.uses_drops":                 ["de": "Nutzt Drops",                      "en": "Uses Drops"],
    "profile.search_name":                ["de": "Name suchen…",                     "en": "Search name..."],
    "profile.remove_suggestion":          ["de": "Vorschlag entfernen",              "en": "Remove Suggestion"],
    "profile.newly_added":                ["de": "Neu hinzugefügt",                  "en": "Newly Added"],
    "profile.your_friend":                ["de": "Dein Freund auf Drops",            "en": "Your Friend on Drops"],
    "profile.add_friends_nav":            ["de": "Freunde hinzufügen",               "en": "Add Friends"],
    "profile.very_reliable":              ["de": "Sehr zuverlässig",                 "en": "Very Reliable"],
    "profile.reliable":                   ["de": "Zuverlässig",                      "en": "Reliable"],
    "profile.average":                    ["de": "Durchschnittlich",                 "en": "Average"],
    "profile.reliability_score":          ["de": "Zuverlässigkeits-Score",           "en": "Reliability Score"],
    "profile.block_user":                 ["de": "{name} blockieren",                "en": "Block {name}"],
    "profile.confirm_block_title":        ["de": "Nutzer blockieren?",               "en": "Block User?"],
    "profile.block_message":              ["de": "{name} wird von der Karte und dem Umgebungs-Tab ausgeblendet.", "en": "{name} will be hidden from the map and nearby tab."],
    "profile.verification_required_title":["de": "Ausweis-Verifizierung erforderlich","en": "ID Verification Required"],
    "profile.verification_required_message":["de": "Nur verifizierte Nutzer können Drops beitreten und erstellen. Das schützt alle in der Community.", "en": "Only verified users can join and create Drops. This protects everyone in the community."],
    "profile.scan_id":                    ["de": "Ausweis jetzt scannen",            "en": "Scan ID Now"],

    // ── Drop Summary ─────────────────────────────────────────────
    "drop_summary.title":      ["de": "Drop-Zusammenfassung",   "en": "Drop Summary"],
    "drop_summary.there":      ["de": "Dabei",                  "en": "There"],
    "drop_summary.reliability":["de": "⌀ Zuverlässigkeit",      "en": "Ø Reliability"],
    "drop_summary.appeared":   ["de": "Erschienen",             "en": "Appeared"],

    // ── Settings – Extended ──────────────────────────────────────
    "settings.security":                  ["de": "Sicherheit",                       "en": "Security"],
    "settings.drops_radius":              ["de": "Drops Radius",                     "en": "Drops Radius"],
    "settings.privacy_account":           ["de": "Datenschutz & Konto",              "en": "Privacy & Account"],
    "settings.visibility_info":           ["de": "Für die Live Karte",               "en": "For the Live Map"],
    "settings.visibility_friends_only":   ["de": "Nur für fremde Drops – Freunde immer sichtbar.", "en": "Only for other people's drops — friends always visible."],
    "settings.youth_protection":          ["de": "Jugendschutz aktiv",               "en": "Youth Protection Active"],
    "settings.locked_until":              ["de": "Gesperrt bis du 18 Jahre alt bist","en": "Locked until you are 18 years old"],
    "settings.your_age_group":            ["de": "Deine Altersgruppe",               "en": "Your Age Group"],
    "settings.your_group":                ["de": "Deine Gruppe",                     "en": "Your Group"],
    "settings.age_restricted_msg":        ["de": "Ab 30 Jahren wird die Altersgruppe 16–21 automatisch gesperrt – zum Schutz jüngerer Nutzer. Du kannst weiterhin alle anderen Altersgruppen auswählen.", "en": "From age 30, the 16-21 age group is automatically blocked to protect younger users. You can still select all other age groups."],
    "settings.cannot_see_other_groups":   ["de": "Andere Altersgruppen sind für dich nicht sichtbar", "en": "Other age groups are not visible to you"],
    "settings.see_only_teens":            ["de": "Du siehst nur Drops von 16–21 Jährigen", "en": "You only see drops from 16-21 year olds"],
    "settings.full_access_at_18":         ["de": "Ab 18 Jahren wird die volle Auswahl automatisch freigeschaltet", "en": "Full access is automatically unlocked at age 18"],
    "settings.protected_by_id":           ["de": "Diese Einstellung ist durch das Geburtsdatum deines Ausweises geschützt", "en": "This setting is protected by your ID's date of birth"],

    // ── Safety – Extended ────────────────────────────────────────
    "safety.active":            ["de": "Aktiv",                                 "en": "Active"],
    "safety.inactive":          ["de": "Inaktiv",                               "en": "Inactive"],
    "safety.warning_active":    ["de": "Warnung aktiv für diesen Bereich",      "en": "Warning active for this area"],
    "safety.set_when_home":     ["de": "Tippe wenn du zuhause bist",            "en": "Tap when you're at home"],
    "safety.warning_radius":    ["de": "Warnradius",                            "en": "Warning Radius"],
    "safety.emergency_alert":   ["de": "Wird bei SOS-Alarm sofort per Anruf & SMS benachrichtigt.", "en": "Will be notified immediately by call & SMS during SOS alarm."],
    "safety.sos_location":      ["de": "SOS: Standort an Umgebung",             "en": "SOS: Share Location with Surroundings"],
    "safety.sos_description":   ["de": "Sendet deinen Standort bei SOS an alle Nutzer in der Nähe", "en": "Sends your location to all nearby users during SOS"],
    "safety.always_on":         ["de": "Immer an",                              "en": "Always On"],
    "safety.set_home_address":  ["de": "Tippe auf deine Heimadresse",           "en": "Tap your home address"],
    "safety.pick_contact":      ["de": "Aus Kontakten wählen",                  "en": "Choose From Contacts"],
    "safety.manual":            ["de": "oder manuell",                          "en": "or manually"],
    "safety.keep":              ["de": "Behalten",                              "en": "Keep"],
    "safety.choose_other":      ["de": "Anderen Kontakt wählen",                "en": "Choose Different Contact"],
    "safety.auto_send_note":    ["de": "Dein Standort wird im Notfall auch automatisch an alle Drops-Nutzer in deiner unmittelbaren Nähe gesendet.", "en": "Your location will also be automatically sent to all nearby Drops users in case of emergency."],

    // ── Account ──────────────────────────────────────────────────
    "account.logout":               ["de": "Abmelden",                             "en": "Sign Out"],
    "account.delete":               ["de": "Konto löschen",                        "en": "Delete Account"],
    "account.confirm_delete":       ["de": "Konto wirklich löschen?",              "en": "Really Delete Account?"],
    "account.delete_warning":       ["de": "Alle deine Daten werden unwiderruflich gelöscht.", "en": "All your data will be permanently deleted."],
    "account.delete_failed":        ["de": "Konto konnte nicht gelöscht werden",   "en": "Could Not Delete Account"],
    "account.age_restricted_title": ["de": "16–21 nicht verfügbar",               "en": "16–21 Not Available"],
    "account.age_restricted_msg":   ["de": "Ab 30 Jahren wird die Altersgruppe 16–21 automatisch gesperrt – zum Schutz jüngerer Nutzer. Du kannst weiterhin alle anderen Altersgruppen auswählen.", "en": "From age 30, the 16-21 age group is automatically blocked to protect younger users. You can still select all other age groups."],

    // ── Reliability ──────────────────────────────────────────────
    "reliability.title":       ["de": "Zuverlässigkeits-Score",  "en": "Reliability Score"],
    "reliability.how_it_works":["de": "Wie funktioniert der Score?", "en": "How Does the Score Work?"],
    "reliability.no_show":     ["de": "Ein No-Show entsteht, wenn du einem Drop beitrittst und ihn zwischen 5 und 30 Minuten nach dem Beitreten verlässt — oder gar nicht erscheinst.", "en": "A no-show happens when you join a drop and leave between 5 and 30 minutes after joining — or don't show up at all."],

    // ── Forms ────────────────────────────────────────────────────
    "form.name":       ["de": "Name",             "en": "Name"],
    "form.phone":      ["de": "Telefonnummer",     "en": "Phone Number"],
    "form.example":    ["de": "z.B. Mama, Beste Freundin…", "en": "e.g. Mom, Best Friend..."],
    "form.save":       ["de": "Speichern",         "en": "Save"],
    "form.close":      ["de": "Schließen",         "en": "Close"],
    "form.understood": ["de": "Verstanden",        "en": "Understood"],

    // ── Preview ──────────────────────────────────────────────────
    "preview.warning_radius": ["de": "Warnbereich Vorschau", "en": "Warning Area Preview"],

    // ── Status ───────────────────────────────────────────────────
    "status.online":  ["de": "online",  "en": "online"],
    "status.offline": ["de": "offline", "en": "offline"],

    // ── Helpers ──────────────────────────────────────────────────
    "helpers.improves_app": ["de": "Hilft uns die App zu verbessern", "en": "Helps us improve the app"],

    // ── SOS ──────────────────────────────────────────────────────
    "sos.active":                ["de": "SOS Aktiv",                "en": "SOS Active"],
    "sos.label":                 ["de": "SOS",                      "en": "SOS"],
    "sos.activate":              ["de": "SOS aktivieren",           "en": "Activate SOS"],
    "sos.confirm_title":         ["de": "Notruf absetzen?",         "en": "Call Emergency Services?"],
    "sos.safety_info":           ["de": "Sicherheits-Info",         "en": "Safety Info"],
    "sos.message_with_contact":  ["de": "112 wird angerufen · {name} wird benachrichtigt · Dein Standort wird an Drops-Nutzer in der Nähe gesendet.", "en": "Calling 112 · {name} will be notified · Your location is shared with nearby Drops users."],
    "sos.message_no_contact":    ["de": "112 wird angerufen · Dein Standort wird an Drops-Nutzer in der Nähe gesendet. Tipp: Notfallkontakt im Profil hinterlegen.", "en": "Calling 112 · Your location is shared with nearby Drops users. Tip: Add emergency contact in profile."],
    "sos.active_location_shared":["de": "SOS aktiv · Standort wird geteilt", "en": "SOS Active · Location Shared"],
    "sos.users_notified":        ["de": "Alle Drops-Nutzer in der Nähe werden benachrichtigt", "en": "All nearby Drops users will be notified"],

    // ── Map – Extended ───────────────────────────────────────────
    "map.route":              ["de": "Route",                           "en": "Route"],
    "map.calculating_route":  ["de": "Route wird berechnet…",           "en": "Calculating route…"],
    "map.walking":            ["de": "Zu Fuß",                          "en": "Walking"],
    "map.distance":           ["de": "Entfernung",                      "en": "Distance"],
    "map.open_in_maps":       ["de": "Turn-by-Turn in Apple Maps öffnen","en": "Open Turn-by-Turn in Apple Maps"],
    "map.walking_minutes":    ["de": "Min zu Fuß",                      "en": "min walking"],
    "map.away":               ["de": "entfernt",                        "en": "away"],
    "map.navigation":         ["de": "Navigation",                      "en": "Navigation"],
    "map.drops_nearby":       ["de": "Drops in deiner Nähe",            "en": "Drops Near You"],
    "map.verify_for_access":  ["de": "Verifiziere dich, um exakte Standorte zu sehen und beizutreten.", "en": "Verify to see exact locations and join Drops."],
    "map.estimated_minutes":  ["de": "~{m} Min",                        "en": "~{m} min"],
    "map.arrival_approx":     ["de": "Ankunft ca.",                     "en": "Arrival approx."],
    "map.time_of_day":        ["de": "Uhr",                             "en": "o'clock"],
    "map.estimated":          ["de": "Voraussichtlich",                 "en": "Estimated"],
    "map.distance_away":      ["de": "entfernt",                        "en": "away"],

    // ── Drop (Active/Detail) ─────────────────────────────────────
    "drop.open_to_all":          ["de": "Offen für alle",               "en": "Open to All"],
    "drop.my_drop":              ["de": "Dein Drop",                    "en": "Your Drop"],
    "drop.already_here":         ["de": "Sind bereits vor Ort",         "en": "Already on Site"],
    "drop.just_started":         ["de": "Gerade gestartet",             "en": "Just started"],
    "drop.active_minutes":       ["de": "Seit {m} Min aktiv",           "en": "Active for {m} min"],
    "drop.active_hours_minutes": ["de": "Seit {h}h {m}min aktiv",       "en": "Active {h}h {m}min"],
    "drop.active_hours":         ["de": "Seit {h}h aktiv",              "en": "Active {h}h"],
    "drop.started_at":           ["de": "Gestartet {time} Uhr",         "en": "Started {time}"],
    "drop.waiting_for_people":   ["de": "Noch wartet niemand…",         "en": "Waiting for people…"],
    "drop.waiting_for_joiners":  ["de": "Warte auf Leute die joinen…",  "en": "Waiting for people to join…"],
    "drop.end_drop":             ["de": "Drop beenden",                 "en": "End Drop"],
    "drop.confirm_end_title":    ["de": "Drop wirklich beenden?",       "en": "Really End Drop?"],
    "drop.end_drop_message":     ["de": "Dein Drop wird für alle Nutzer in deiner Nähe entfernt.", "en": "Your Drop will be removed for all nearby users."],
    "drop.end":                  ["de": "Beenden",                      "en": "End"],
    "drop.already_active":       ["de": "Du bist bereits in einem Drop aktiv.", "en": "You are already in an active Drop."],
    "drop.leave_active_first":   ["de": "Verlasse zuerst deinen aktiven Drop.", "en": "Leave your active Drop first."],
    "drop.coming_by":            ["de": "Ich komme vorbei",             "en": "I'll Come By"],
    "drop.im_in":                ["de": "Bin dabei!",                   "en": "I'm In!"],
    "drop.arrived":              ["de": "Vor Ort",                      "en": "On Site"],
    "drop.on_the_way":           ["de": "Unterwegs",                    "en": "On The Way"],
    "drop.person_on_way_singular":["de": "1 Person ist unterwegs",      "en": "1 person on the way"],
    "drop.people_on_way_plural": ["de": "{n} Personen sind unterwegs",  "en": "{n} people on the way"],
    "drop.invite_friends":       ["de": "Freunde einladen",             "en": "Invite Friends"],
    "drop.leave_drop":           ["de": "Drop verlassen",               "en": "Leave Drop"],
    "drop.confirm_leave_title":  ["de": "Drop verlassen?",              "en": "Leave Drop?"],
    "drop.leave_warning":        ["de": "Wenn du zwischen 5 und 30 Minuten nach dem Beitreten verlässt, zählt das als No-Show — die andere Person wartet vielleicht schon.", "en": "Leaving within 5-30 minutes of joining counts as a no-show — the other person might be waiting."],
    "drop.my_drop_active":       ["de": "Dein Drop · Aktiv",            "en": "Your Drop · Active"],
    "drop.waiting_title":        ["de": "Noch wartet niemand…",         "en": "Waiting for people…"],
    "drop.waiting_description":  ["de": "Lade Freunde ein oder warte auf Spontan-Joiner in deiner Nähe.", "en": "Invite friends or wait for spontaneous joiners nearby."],
    "drop.share_message":        ["de": "Ich bin gerade bei einem {activity}-Drop in München! Komm vorbei 📍 – LinkUp App", "en": "I'm at a {activity} Drop in Munich right now! Come by 📍 – LinkUp App"],
    "drop.participants":         ["de": "Teilnehmer",                   "en": "Participants"],
    "drop.full":                 ["de": "Voll",                         "en": "Full"],
    "drop.at_location":          ["de": "Vor Ort",                      "en": "On Site"],
    "drop.at_location_short":    ["de": "vor Ort",                      "en": "on site"],
    "drop.on_way_short":         ["de": "unterwegs",                    "en": "on the way"],
    "drop.arrived_short":        ["de": "vor Ort",                      "en": "arrived"],
    "drop.heading_to_drop":      ["de": "Unterwegs zum Drop",           "en": "Heading to Drop"],
    "drop.details_locked":       ["de": "Details werden freigeschaltet","en": "Details will be unlocked"],
    "drop.arrive_for_unlock":    ["de": "Komm an — Bluetooth bestätigt deine Ankunft", "en": "Arrive — Bluetooth confirms your arrival"],
    "drop.one_person_on_way":    ["de": "1 Person ist unterwegs",       "en": "1 person on the way"],
    "drop.n_people_on_way":      ["de": "{n} Personen sind unterwegs",  "en": "{n} people on the way"],

    // ── Create Drop – Extended ───────────────────────────────────
    "create.what_doing":          ["de": "Was macht ihr?",              "en": "What are you doing?"],
    "create.activity_placeholder":["de": "z.B. Fußball, Kaffee, Wandern…", "en": "e.g. Soccer, Coffee, Hiking…"],
    "create.what_planned":        ["de": "Was ist geplant?",            "en": "What's planned?"],
    "create.description_placeholder":["de": "Kurze Info – was macht ihr, worauf freut ihr euch?", "en": "Brief info – what are you doing, what are you looking forward to?"],
    "create.when":                ["de": "Wann?",                       "en": "When?"],
    "create.time":                ["de": "Uhrzeit",                     "en": "Time"],
    "create.in_15_min":           ["de": "In 15 Min",                   "en": "In 15 min"],
    "create.in_30_min":           ["de": "In 30 Min",                   "en": "In 30 min"],
    "create.in_45_min":           ["de": "In 45 Min",                   "en": "In 45 min"],
    "create.in_1_hour":           ["de": "In 1 Std",                    "en": "In 1 hour"],
    "create.in_2_hours":          ["de": "In 2 Std",                    "en": "In 2 hours"],
    "create.max_participants":    ["de": "Max. Teilnehmer",             "en": "Max. Participants"],
    "create.people":              ["de": "Personen",                    "en": "people"],
    "create.current_location":    ["de": "Aktueller Standort",          "en": "Current Location"],
    "create.your_current_location":["de": "Dein jetziger Standort",     "en": "Your current location"],
    "create.search_location":     ["de": "Ort suchen",                  "en": "Search Location"],
    "create.search_placeholder":  ["de": "Café, Bar, Park, Adresse…",   "en": "Café, Bar, Park, Address…"],
    "create.type_search":         ["de": "Tippe um einen Ort zu suchen","en": "Type to search a location"],
    "create.set_pin":             ["de": "Pin setzen",                  "en": "Set Pin"],
    "create.pin_set":             ["de": "Pin gesetzt ✓",               "en": "Pin set ✓"],
    "create.manually_on_map":     ["de": "Manuell auf der Karte",       "en": "Manually on the map"],
    "create.on_map":              ["de": "Auf Karte tippen",            "en": "Tap on map"],
    "create.drop_live":           ["de": "Drop ist live! Freunde in der Nähe werden benachrichtigt.", "en": "Drop is live! Friends nearby will be notified."],
    "create.id_required":         ["de": "Ausweis erforderlich",        "en": "ID Required"],
    "create.verify_once":         ["de": "Verifiziere dich einmalig um Drops zu erstellen.", "en": "Verify yourself once to create Drops."],
    "create.specify_activity":    ["de": "Gib zuerst an, was ihr macht.","en": "First specify what you're doing."],
    "create.only_in_munich":      ["de": "Drops sind aktuell nur in München verfügbar.", "en": "Drops are currently only available in Munich."],
    "create.confirm_pin":         ["de": "Pin bestätigen ✓",            "en": "Confirm Pin ✓"],
    "create.tap_map":             ["de": "Tippe auf die Karte",         "en": "Tap the map"],
    "create.tap_on_map":          ["de": "Tippe auf die Karte",         "en": "Tap on the map"],
    "create.create_anyway":       ["de": "Trotzdem erstellen",          "en": "Create anyway"],

    // ── Shared Components ────────────────────────────────────────
    "shared.no_drops_nearby":  ["de": "Keine Drops in der Nähe",        "en": "No Drops nearby"],
    "shared.be_first_drop":    ["de": "Sei der Erste und erstell einen Drop –\noder erweitere deinen Radius in den Einstellungen.", "en": "Be the first and create a Drop –\nor expand your radius in settings."],
    "shared.no_friends":       ["de": "Noch keine Freunde",             "en": "No friends yet"],
    "shared.meet_drop":        ["de": "Triff jemanden bei einem Drop und bestätige die Begegnung – so entstehen Verbindungen.", "en": "Meet someone at a Drop and confirm the meeting – connections are made this way."],
    "shared.sharing_drop":     ["de": "teilt gerade einen Drop auf Drops.", "en": "is sharing a Drop on Drops."],

    // ── Design System ────────────────────────────────────────────
    "design.start_drop":              ["de": "Drop starten",            "en": "Start Drop"],
    "design.very_reliable":           ["de": "Sehr zuverlässig",        "en": "Very reliable"],
    "design.reliable":                ["de": "Zuverlässig",             "en": "Reliable"],
    "design.average":                 ["de": "Durchschnittlich",        "en": "Average"],
    "design.unreliable":              ["de": "Unzuverlässig",           "en": "Unreliable"],
    "design.new":                     ["de": "Neu",                     "en": "New"],
    "design.no_drops_yet":            ["de": "Noch keine Drops",        "en": "No Drops yet"],
    "design.drops_attended":          ["de": "von Drops erschienen",    "en": "of Drops attended"],
    "design.emergency_share_location":["de": "Notfall – Standort teilen","en": "Emergency – Share location"],
    "design.location_sent":           ["de": "Standort gesendet ✓",     "en": "Location sent ✓"],
    "design.location_sent_notified":  ["de": "Dein Kontakt wurde benachrichtigt", "en": "Your contact has been notified"],
    "design.send_location_immediately":["de": "Sendet deinen Standort sofort", "en": "Sends your location immediately"],
    "design.verified_users":          ["de": "Verifizierte Nutzer",     "en": "Verified Users"],
    "design.all_verified_by_id":      ["de": "Alle per Ausweis-Scan verifiziert", "en": "All verified by ID scan"],
    "design.reliability_score":       ["de": "Reliability Score",       "en": "Reliability Score"],
    "design.no_shows_reported":       ["de": "No-Shows werden nach 30 Min gemeldet", "en": "No-shows reported after 30 min"],
    "design.one_tap_block":           ["de": "1-Tap blockieren",        "en": "1-Tap Block"],
    "design.block_immediately":       ["de": "Sofort und ohne Erklärung","en": "Immediately and without explanation"],
    "design.safety":                  ["de": "Sicherheit",               "en": "Safety"],
    "design.done":                    ["de": "Fertig",                  "en": "Done"],
    "design.limited_access":          ["de": "Eingeschränkter Zugang",  "en": "Limited Access"],
    "design.verify_id_full_access":   ["de": "Verifiziere deinen Ausweis für vollen Zugang", "en": "Verify your ID for full access"],
    "design.precise_drop_locations":  ["de": "Genaue Drop-Standorte",   "en": "Precise Drop locations"],
    "design.create_drops":            ["de": "Drops erstellen",         "en": "Create Drops"],
    "design.join_drops":              ["de": "Drops beitreten",         "en": "Join Drops"],
    "design.add_friends":             ["de": "Freunde hinzufügen",      "en": "Add friends"],

    // ── Feed – Extended ──────────────────────────────────────────
    "feed.user":          ["de": "Drops-Nutzer",        "en": "Drops user"],
    "feed.available_now": ["de": "Gerade verfügbar",    "en": "Available now"],
    "feed.unknown":       ["de": "Unbekannt",           "en": "Unknown"],
    "feed.joining":       ["de": "dabei",               "en": "joining"],

    // ── City Gate ────────────────────────────────────────────────
    "city.not_in_city":         ["de": "Noch nicht in deiner Stadt",    "en": "Not in your city yet"],
    "city.notification_request":["de": "Möchtest du benachrichtigt werden wenn Drops in deine Stadt kommt? Schreib uns: hello@drops.app", "en": "Want to be notified when Drops comes to your city? Write us: hello@drops.app"],

    // ── Common – Extended ────────────────────────────────────────
    "common.later":    ["de": "Später",    "en": "Later"],
    "common.or":       ["de": "oder",      "en": "or"],
    "common.sign_in":  ["de": "Einloggen", "en": "Sign in"],

    // ── Onboarding – Extended ────────────────────────────────────
    "onboard.access_denied":         ["de": "Zugang nicht möglich",        "en": "Access Denied"],
    "onboard.account_exists":        ["de": "Mit diesen Ausweisdaten existiert bereits ein Drops-Konto. Bitte melde dich mit deiner registrierten Methode an.", "en": "An account with this ID data already exists. Please sign in with your registered method."],
    "onboard.age_private":           ["de": "Dein genaues Alter wird nie öffentlich angezeigt.", "en": "Your exact age will never be shown publicly."],
    "onboard.already_registered":    ["de": "Bereits registriert?",         "en": "Already registered?"],
    "onboard.analyzing_id":          ["de": "Ausweis wird analysiert…",     "en": "Analyzing ID…"],
    "onboard.beta_quick_start":      ["de": "Beta-Schnelleinstieg (ohne Account)", "en": "Beta Quick Start (no account)"],
    "onboard.birthdate":             ["de": "Geburtsdatum",                 "en": "Birthdate"],
    "onboard.birthdate_mismatch":    ["de": "Das Geburtsdatum auf deinem Ausweis stimmt nicht mit dem angegebenen Datum überein. Für dieses Ausweis-Dokument muss ein neues Konto erstellt werden.", "en": "The birthdate on your ID does not match the entered date. A new account must be created for this ID document."],
    "onboard.birthdate_usage":       ["de": "Wird nur für die Altersverifikation\nund passende Drops verwendet.", "en": "Used only for age verification\nand matching Drops."],
    "onboard.biometric_failed":      ["de": "Biometrie fehlgeschlagen – bitte mit SMS einloggen.", "en": "Biometric authentication failed – please sign in with SMS."],
    "onboard.code_sent_to":          ["de": "Gesendet an {phoneNumber}",    "en": "Sent to {phoneNumber}"],
    "onboard.code_verify_failed":    ["de": "Code konnte nicht verifiziert werden. Bitte nochmal versuchen.", "en": "Code could not be verified. Please try again."],
    "onboard.comparing_face":        ["de": "Gesicht wird verglichen…",     "en": "Comparing face…"],
    "onboard.confirm":               ["de": "Bestätigen",                   "en": "Confirm"],
    "onboard.confirm_all":           ["de": "Alles bestätigen",             "en": "Confirm all"],
    "onboard.confirm_identity":      ["de": "Identität bestätigen",         "en": "Confirm Identity"],
    "onboard.continue_as_phone":     ["de": "Weiter als {phone}",           "en": "Continue as {phone}"],
    "onboard.continue_ellipsis":     ["de": "Weiter…",                      "en": "Continue…"],
    "onboard.continue_face_id":      ["de": "Mit Face ID fortfahren",       "en": "Continue with Face ID"],
    "onboard.continue_touch_id":     ["de": "Mit Touch ID fortfahren",      "en": "Continue with Touch ID"],
    "onboard.choose_id_document":    ["de": "Wähle dein Ausweisdokument",   "en": "Choose your ID document"],
    "onboard.detected":              ["de": "Erkannt",                      "en": "Detected"],
    "onboard.delete_account_deletes_data":["de": "Konto löschen = alle Daten sofort weg", "en": "Delete account = all data deleted immediately"],
    "onboard.deletable_anytime":     ["de": "Jederzeit löschbar",           "en": "Deletable anytime"],
    "onboard.data_stays_with_us":    ["de": "Deine Daten bleiben ausschließlich bei uns", "en": "Your data stays exclusively with us"],
    "onboard.enter_code":            ["de": "Code eingeben",                "en": "Enter Code"],
    "onboard.enter_real_name":       ["de": "Bitte gib deinen echten Namen und Geburtstag an.", "en": "Please enter your real name and birthdate."],
    "onboard.faceid_reason":         ["de": "Mit Face ID in Drops einloggen","en": "Sign in to Drops with Face ID"],
    "onboard.first_name":            ["de": "Vorname",                      "en": "First Name"],
    "onboard.from_id_check":         ["de": "Vom Ausweis übernommen – bitte prüfen", "en": "From ID – please verify"],
    "onboard.id_benefits":           ["de": "Verschlüsselt · Einmalig geprüft · Jederzeit löschbar", "en": "Encrypted · Verified once · Deletable anytime"],
    "onboard.id_consent":            ["de": "Ich stimme der einmaligen Identitätsverifizierung gemäß DSGVO zu.", "en": "I agree to one-time identity verification according to GDPR."],
    "onboard.id_country_code":       ["de": "D",                            "en": "D"],
    "onboard.id_is_mine":            ["de": "Dieser Ausweis gehört mir",    "en": "This ID belongs to me"],
    "onboard.id_ownership":          ["de": "Dieser Ausweis gehört mir und wird nicht missbraucht", "en": "This ID belongs to me and will not be misused"],
    "onboard.invalid_phone":         ["de": "Bitte gib eine gültige Nummer ein.", "en": "Please enter a valid phone number."],
    "onboard.legal_notice":          ["de": "Diese Prüfung erfolgt gemäß §§ 1, 2 JuSchG und ist gesetzlich vorgeschrieben.", "en": "This verification is required by law according to §§ 1, 2 JuSchG."],
    "onboard.lets_go":               ["de": "Los geht's!",                  "en": "Let's go!"],
    "onboard.location_set":          ["de": "Standort gesetzt ✓",           "en": "Location set ✓"],
    "onboard.manual_trigger":        ["de": "Manuell auslösen",             "en": "Trigger Manually"],
    "onboard.mrz_detected":          ["de": "MRZ erkannt!",                 "en": "MRZ Detected!"],
    "onboard.mrz_example":           ["de": "So sieht der MRZ-Streifen aus","en": "Here's what the MRZ strip looks like"],
    "onboard.mrz_label":             ["de": "MRZ",                          "en": "MRZ"],
    "onboard.must_be_16":            ["de": "Du musst mindestens 16 Jahre alt sein.", "en": "You must be at least 16 years old."],
    "onboard.no_account_question":   ["de": "Noch kein Account?",           "en": "No account?"],
    "onboard.no_account_register":   ["de": "Noch kein Account? Jetzt registrieren", "en": "No account? Register now"],
    "onboard.no_sharing":            ["de": "Keine Weitergabe",             "en": "No sharing"],
    "onboard.only_mrz_data":         ["de": "Nur MRZ-Daten",               "en": "MRZ data only"],
    "onboard.passport_photo_mrz":    ["de": "Datenseite mit Foto · MRZ",    "en": "Photo page with photo · MRZ"],
    "onboard.phone_number":          ["de": "Handynummer",                  "en": "Phone Number"],
    "onboard.pipe":                  ["de": "|",                             "en": "|"],
    "onboard.privacy_policy_link":   ["de": "Datenschutzerklärung →",       "en": "Privacy Policy →"],
    "onboard.register_now":          ["de": "Jetzt registrieren",           "en": "Register now"],
    "onboard.register_phone":        ["de": "Mit Handynummer registrieren", "en": "Register with phone number"],
    "onboard.retake":                ["de": "Nochmal aufnehmen",            "en": "Retake"],
    "onboard.saved_number":          ["de": "Gespeicherte Nummer",          "en": "Saved number"],
    "onboard.scan_again":            ["de": "Bitte nochmal scannen oder Rückseite des Ausweises verwenden", "en": "Please scan again or use the back of your ID"],
    "onboard.scan_id":               ["de": "Ausweis scannen",              "en": "Scan ID"],
    "onboard.scan_id_back":          ["de": "Rückseite scannen",            "en": "Scan ID back"],
    "onboard.scan_passport":         ["de": "Reisepass scannen",            "en": "Scan Passport"],
    "onboard.searching_mrz":         ["de": "MRZ-Streifen wird gesucht …",  "en": "Searching for MRZ strip…"],
    "onboard.send_again":            ["de": "Erneut senden",                "en": "Send again"],
    "onboard.send_again_countdown":  ["de": "Erneut senden in {countdown}s","en": "Send again in {countdown}s"],
    "onboard.send_code":             ["de": "Code senden",                  "en": "Send Code"],
    "onboard.send_code_arrow":       ["de": "Code senden →",               "en": "Send Code →"],
    "onboard.send_code_message":     ["de": "Wir senden dir einen einmaligen Bestätigungscode.", "en": "We'll send you a one-time verification code."],
    "onboard.setup_later_settings":  ["de": "Später in Einstellungen einrichten", "en": "Set up later in settings"],
    "onboard.sign_in_arrow":         ["de": "Einloggen →",                  "en": "Sign in →"],
    "onboard.sign_in_face_id":       ["de": "Mit Face ID anmelden",         "en": "Sign in with Face ID"],
    "onboard.sign_in_phone":         ["de": "Mit Handynummer einloggen",    "en": "Sign in with phone number"],
    "onboard.sign_in_touch_id":      ["de": "Mit Touch ID anmelden",        "en": "Sign in with Touch ID"],
    "onboard.six_digit_code":        ["de": "6-stelliger Code",             "en": "6-digit code"],
    "onboard.skip_verification":     ["de": "Ohne Verifizierung fortfahren","en": "Continue Without Verification"],
    "onboard.start_camera":          ["de": "Kamera starten",               "en": "Start Camera"],
    "onboard.tap_map_to_set_location":["de": "Tippe auf die Karte um deinen Standort zu setzen.", "en": "Tap the map to set your location."],
    "onboard.tap_to_place":          ["de": "Tippe zum Platzieren",         "en": "Tap to place"],
    "onboard.tos_notice":            ["de": "Mit der Registrierung stimmst du unseren Nutzungsbedingungen zu.", "en": "By registering, you agree to our Terms of Service."],
    "onboard.touchid_reason":        ["de": "Mit Touch ID in Drops einloggen","en": "Sign in to Drops with Touch ID"],
    "onboard.underage_message":      ["de": "Drops ist ausschließlich für Personen ab 16 Jahren.\n\nDein Ausweis zeigt, dass du diese Altersgrenze noch nicht erreicht hast. Eine Nutzung ist leider nicht möglich.", "en": "Drops is only available for people 16 years and older.\n\nYour ID shows that you have not yet reached this age limit. Unfortunately, you cannot use the app."],
    "onboard.welcome_back":          ["de": "Willkommen zurück",            "en": "Welcome back"],
    "onboard.where_are_you":         ["de": "Wo bist du?",                  "en": "Where are you?"],
    "onboard.years":                 ["de": "Jahre",                        "en": "years"],
    "onboard.your_birthdate":        ["de": "Dein Geburtsdatum",            "en": "Your Birthdate"],
    "onboard.your_details":          ["de": "Deine Angaben",                "en": "Your details"],
]

// MARK: - tr() Helper

/// Gibt den lokalisierten String für den aktuellen `appLanguage`-Wert zurück.
/// Liest direkt aus UserDefaults — wird automatisch aktualisiert wenn eine
/// View `@AppStorage("appLanguage")` als DynamicProperty enthält.
func tr(_ key: String) -> String {
    // Aktuell nur Deutsch — English wird später wieder aktiviert
    return strings[key]?["de"] ?? key
}
